repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-yaml

- repo: local
  hooks:
  - id: security-check
    name: Security Check
    entry: bash -c '
      if grep -r "password\|secret\|api[_-]key" . --exclude-dir=.git --exclude="*.md"; then
        echo "❌ Potential sensitive data found!";
        exit 1;
      fi;
      echo "✅ Security check passed";
    '
    language: system
    pass_filenames: false

  - id: domain-check
    name: Domain Exposure Check
    entry: bash -c '
      if grep -r "init0xff\.com" app/ 2>/dev/null; then
        echo "❌ Domain exposure detected in code!";
        exit 1;
      fi;
      echo "✅ Domain check passed";
    '
    language: system
    pass_filenames: false