apiVersion: apps/v1
kind: Deployment
metadata:
  name: st-josephs-demo
  namespace: st-josephs-demo
  labels:
    app: st-josephs-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: st-josephs-demo
  template:
    metadata:
      labels:
        app: st-josephs-demo
    spec:
      containers:
      - name: app
        image: nixndme/st-josephs-demo:v1.0.11
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "v1.0.11"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
